name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    container:
      image: mariojim/resume-portfolio:latest
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}
        GRAPHQL_GITHUB_KEY: ${{ secrets.GRAPHQL_GITHUB_KEY }}
        API_KEY_GITHUB_REPO: ${{ secrets.API_KEY_GITHUB_REPO }}

    steps:
      - name: Clone source
        uses: actions/checkout@v3
        with:
          path: 'source'

      - name: Run linter
        run: make -C source lint

      - name: Build website
        run: make -C source

      - name: Clone website repo
        uses: actions/checkout@v3
        with:
          repository: MarioJim/mariojim.github.io
          path: 'website'
          token: ${{ secrets.API_KEY_GITHUB_REPO }}

      - name: Add files
        run: |
          cd website
          git rm -r *
          git reset HEAD LICENSE README.md
          mv ../source/build/* .
          git add *

      - name: Push website repo
        run: |
          cd website
          git config --global user.name "MarioJim"
          git config --global user.email "mario.emilio.j@gmail.com"
          git commit -m "[CD] $COMMIT_MSG"
          git push
