name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Continuous Deployment to mariojim.github.io
    runs-on: ubuntu-latest
    container:
      image: mariojim/resume-portfolio:latest
      env:
        GRAPHQL_GITHUB_KEY: ${{ secrets.GRAPHQL_GITHUB_KEY }}
        API_KEY_GITHUB_REPO: ${{ secrets.API_KEY_GITHUB_REPO }}

    steps:
      - name: Clone source
        uses: actions/checkout@v2
        with:
          path: 'source'

      - name: Clone website repo
        uses: actions/checkout@v2
        with:
          repository: MarioJim/mariojim.github.io
          path: 'website'
          token: ${{ secrets.API_KEY_GITHUB_REPO }}

      - name: Build website
        run: |
          cd source
          ./build.sh
          cd ../website
          git rm -r .
          git restore --staged LICENSE README.md
          mv ../source/portfolio/public/* .
          git add *

      - name: Push website repo
        run: |
          cd website
          git config --global user.name "MarioJim"
          git config --global user.email "mario.emilio.j@gmail.com"
          git commit -m "[CD] $(git log -1 --pretty=%B)"
          git push
